### ISSUE TITLE
Should be twice as long (or possibly wide) as standard RTG

### ISSUE THREAD

**Issue by Ruedii** [ColorCurves/AeroRTG#1]
Do to this form factor having roughly half the surface area, it should be either twice as wide or twice as long as the the stock RTG.  

The other option, is to have the RTG have longer fins, but that is a less aerodynamic option.

**Comment by Bezzier** [comment]
It took me a while to understand what you meant. how about if we change the material instead, so that it's either heavier or hotter? The size would be hard to double.

**Comment by Ruedii** [comment]
If the heat sink is simply more effective this wouldn't necessarily be the
case.  We could presume that instead.  Simply make it more expensive.

**Comment by Bezzier** [comment]
Agreed.  Will increase expense by 50% because there is an in-game benefit to using this instead of the standard RTG.

**Comment by Bezzier** [comment]
Solved.
